version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: videoapp
      POSTGRES_PASSWORD: videoapp
      POSTGRES_DB: videoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
